name: game_of_life
description: My implemetation of the famous cellular automaton

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: 2.10.3

dependencies:
  flutter:
    sdk: flutter

  numberpicker: ^2.1.1
  file_picker: ^4.5.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
